var bvharconfig_8h =
[
    [ "RegParams", "structbvhar_1_1RegParams.html", "structbvhar_1_1RegParams" ],
    [ "SvParams", "structbvhar_1_1SvParams.html", "structbvhar_1_1SvParams" ],
    [ "MinnParams", "structbvhar_1_1MinnParams.html", "structbvhar_1_1MinnParams" ],
    [ "HierminnParams", "structbvhar_1_1HierminnParams.html", "structbvhar_1_1HierminnParams" ],
    [ "SsvsParams", "structbvhar_1_1SsvsParams.html", "structbvhar_1_1SsvsParams" ],
    [ "HorseshoeParams", "structbvhar_1_1HorseshoeParams.html", "structbvhar_1_1HorseshoeParams" ],
    [ "NgParams", "structbvhar_1_1NgParams.html", "structbvhar_1_1NgParams" ],
    [ "DlParams", "structbvhar_1_1DlParams.html", "structbvhar_1_1DlParams" ],
    [ "GdpParams", "structbvhar_1_1GdpParams.html", "structbvhar_1_1GdpParams" ],
    [ "RegInits", "structbvhar_1_1RegInits.html", "structbvhar_1_1RegInits" ],
    [ "LdltInits", "structbvhar_1_1LdltInits.html", "structbvhar_1_1LdltInits" ],
    [ "SvInits", "structbvhar_1_1SvInits.html", "structbvhar_1_1SvInits" ],
    [ "HierminnInits", "structbvhar_1_1HierminnInits.html", "structbvhar_1_1HierminnInits" ],
    [ "SsvsInits", "structbvhar_1_1SsvsInits.html", "structbvhar_1_1SsvsInits" ],
    [ "GlInits", "structbvhar_1_1GlInits.html", "structbvhar_1_1GlInits" ],
    [ "HsInits", "structbvhar_1_1HsInits.html", "structbvhar_1_1HsInits" ],
    [ "NgInits", "structbvhar_1_1NgInits.html", "structbvhar_1_1NgInits" ],
    [ "GdpInits", "structbvhar_1_1GdpInits.html", "structbvhar_1_1GdpInits" ],
    [ "RegRecords", "structbvhar_1_1RegRecords.html", "structbvhar_1_1RegRecords" ],
    [ "SparseRecords", "structbvhar_1_1SparseRecords.html", "structbvhar_1_1SparseRecords" ],
    [ "LdltRecords", "structbvhar_1_1LdltRecords.html", "structbvhar_1_1LdltRecords" ],
    [ "SvRecords", "structbvhar_1_1SvRecords.html", "structbvhar_1_1SvRecords" ],
    [ "SsvsRecords", "structbvhar_1_1SsvsRecords.html", "structbvhar_1_1SsvsRecords" ],
    [ "GlobalLocalRecords", "structbvhar_1_1GlobalLocalRecords.html", "structbvhar_1_1GlobalLocalRecords" ],
    [ "HorseshoeRecords", "structbvhar_1_1HorseshoeRecords.html", "structbvhar_1_1HorseshoeRecords" ],
    [ "NgRecords", "structbvhar_1_1NgRecords.html", "structbvhar_1_1NgRecords" ],
    [ "initialize_record", "bvharconfig_8h.html#a1c28510c1a60c0d61f1fc7ccadd03fd9", null ],
    [ "initialize_record", "bvharconfig_8h.html#a6c0609624e6286035939a41a47027e68", null ]
];