var bvharconfig_8h =
[
    [ "bvhar::RegParams", "structbvhar_1_1RegParams.html", "structbvhar_1_1RegParams" ],
    [ "bvhar::SvParams", "structbvhar_1_1SvParams.html", "structbvhar_1_1SvParams" ],
    [ "bvhar::MinnParams< BaseRegParams >", "structbvhar_1_1MinnParams.html", "structbvhar_1_1MinnParams" ],
    [ "bvhar::HierminnParams< BaseRegParams >", "structbvhar_1_1HierminnParams.html", "structbvhar_1_1HierminnParams" ],
    [ "bvhar::SsvsParams< BaseRegParams >", "structbvhar_1_1SsvsParams.html", "structbvhar_1_1SsvsParams" ],
    [ "bvhar::HorseshoeParams< BaseRegParams >", "structbvhar_1_1HorseshoeParams.html", "structbvhar_1_1HorseshoeParams" ],
    [ "bvhar::NgParams< BaseRegParams >", "structbvhar_1_1NgParams.html", "structbvhar_1_1NgParams" ],
    [ "bvhar::DlParams< BaseRegParams >", "structbvhar_1_1DlParams.html", "structbvhar_1_1DlParams" ],
    [ "bvhar::GdpParams< BaseRegParams >", "structbvhar_1_1GdpParams.html", "structbvhar_1_1GdpParams" ],
    [ "bvhar::RegInits", "structbvhar_1_1RegInits.html", "structbvhar_1_1RegInits" ],
    [ "bvhar::LdltInits", "structbvhar_1_1LdltInits.html", "structbvhar_1_1LdltInits" ],
    [ "bvhar::SvInits", "structbvhar_1_1SvInits.html", "structbvhar_1_1SvInits" ],
    [ "bvhar::HierminnInits< BaseRegInits >", "structbvhar_1_1HierminnInits.html", "structbvhar_1_1HierminnInits" ],
    [ "bvhar::SsvsInits< BaseRegInits >", "structbvhar_1_1SsvsInits.html", "structbvhar_1_1SsvsInits" ],
    [ "bvhar::GlInits< BaseRegInits >", "structbvhar_1_1GlInits.html", "structbvhar_1_1GlInits" ],
    [ "bvhar::HsInits< BaseRegInits >", "structbvhar_1_1HsInits.html", "structbvhar_1_1HsInits" ],
    [ "bvhar::NgInits< BaseRegInits >", "structbvhar_1_1NgInits.html", "structbvhar_1_1NgInits" ],
    [ "bvhar::GdpInits< BaseRegInits >", "structbvhar_1_1GdpInits.html", "structbvhar_1_1GdpInits" ],
    [ "bvhar::RegRecords", "structbvhar_1_1RegRecords.html", "structbvhar_1_1RegRecords" ],
    [ "bvhar::SparseRecords", "structbvhar_1_1SparseRecords.html", "structbvhar_1_1SparseRecords" ],
    [ "bvhar::LdltRecords", "structbvhar_1_1LdltRecords.html", "structbvhar_1_1LdltRecords" ],
    [ "bvhar::SvRecords", "structbvhar_1_1SvRecords.html", "structbvhar_1_1SvRecords" ],
    [ "bvhar::SsvsRecords", "structbvhar_1_1SsvsRecords.html", "structbvhar_1_1SsvsRecords" ],
    [ "bvhar::GlobalLocalRecords", "structbvhar_1_1GlobalLocalRecords.html", "structbvhar_1_1GlobalLocalRecords" ],
    [ "bvhar::HorseshoeRecords", "structbvhar_1_1HorseshoeRecords.html", "structbvhar_1_1HorseshoeRecords" ],
    [ "bvhar::NgRecords", "structbvhar_1_1NgRecords.html", "structbvhar_1_1NgRecords" ],
    [ "initialize_record", "bvharconfig_8h.html#a1c28510c1a60c0d61f1fc7ccadd03fd9", null ],
    [ "initialize_record", "bvharconfig_8h.html#a6c0609624e6286035939a41a47027e68", null ]
];